license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="EaseCation"
description='''
Redirects persistent player-owned mod configuration, resource packs, and Iris shader packs away from launcher-cleaned directories.
'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="immediatelyfast"
type="optional"
versionRange="[0,)"
ordering="BEFORE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="iris"
type="optional"
versionRange="[0,)"
ordering="BEFORE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="sodium"
type="optional"
versionRange="[0,)"
ordering="BEFORE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="yet_another_config_lib_v3"
type="optional"
versionRange="[0,)"
ordering="BEFORE"
side="CLIENT"
